### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by feliwir** [thosakwe/paypal_dart#3]
Hey, how to use this API?

**Comment by thosakwe** [comment]
There are no examples because I haven’t touched this in 3 years. It also won’t work with Dart 2, so I recommend just using `package:http` directly. 

That being said, I’ll probably archive+discontinue this library, as I have no intention of ever completing it.

**Comment by feliwir** [comment]
Okay, i understand that, eventhough i'd find a working Paypal API very useful
